{% set version = "3.0.0" %}
{% set name = "zict" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e321e263b6a97aafc0790c3cfb3c04656b7066e6738c37fffcca95d803c9fba5

build:
  number: 1
  script: "{{ PYTHON }} -m pip install . -vv"
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip

  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - zict

about:
  home: http://github.com/mrocklin/zict
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Composable Dictionary Classes


extra:
  recipe-maintainers:
    - mrocklin
    - jrbourbeau
