{% set version = "2.2.0" %}
{% set name = "zict" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d7366c2e2293314112dcf2432108428a67b927b00005619feefc310d12d833f3

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  noarch: python

requirements:
  build:
    - python >=3.7
    - pip

  run:
    - python >=3.7
    - heapdict

test:
  imports:
    - zict

about:
  home: http://github.com/mrocklin/zict
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Composable Dictionary Classes


extra:
  recipe-maintainers:
    - mrocklin
    - jrbourbeau
