travis:
  secure:
    BINSTAR_TOKEN: nGKXfl6B/Lc4o4k7EdBgjFNcs/joNONSm2VxNLzuK86lVHI63uVYXrMds8j4FKHtTBFkKRA2k2XmaM6S+3LDKC1SL68TzkcJBnFhLXONJwCRroRWvbyePFnoXJ0r7Bwiqi8kJT003mQ1PJRdBNEHfv56RXehLnIyiTO3Q32xU67yOuqY3YitSqGCQSvLhIlyYLIr9Wb6AG8o6jNTIqAuX5so9G1JDi7CjHZYmU0j9hIeieSrt/6f4IBCm7xuygjoXHsven4GFhvFS1C41E4LDyCGUjzpt9fnxSY2mKLVJCxU2ycDf3vSmE/o7AOXsq+LH/XdckzwDKUvKlMtOB0EecTtSXuIM4nAGSdBDFV1EPek0MH4LKv0c8NVVyaYBw4xvTerQpiGE0ny1pOb3d61e9RsKH+fqvhA0YnXC+bCWZjpfJ7onGk9HBZq03iygkFQVh/I3Fz6gGs/HL/S8Ck8J6rC29yV0oxtfDuuXY8O0KBb8NLDOYUr3A+S9mIST+e+dF2+gW1ImUXJ6MNkOg5uPsqD93bOWZ20kfxOmHA23jRR0PQtUd88C/OuLqoASvcRC8W6gydXQXYBcKhaTOg2PFX3JtgyW+D0ldYaBrTtQPSZ6VAlAUGkZ1ZnWjwaBfLXY1TSQTxFaBPCnXvY2depagkHjcOok/vsov3Y0TqJvTU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
